version: '3.7'

volumes:
  logs:
    driver: local

services:
  slim:
    image: php:8-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - logs:/var/www/logs
    links:
      - postgres

  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=scacchieropoli
      - POSTGRES_USER=scacchieropoli
      - POSTGRES_PASSWORD=scacchieropoli
